### ISSUE TITLE
SmartDashboard Git Version Display

### ISSUE THREAD

**Issue by WesleyJ-128** [first95/FRC2024#2]
Display the running code version on SmartDashboard using the manifest.  This is mostly done; the robot code side of reading the manifest is currently-non functional and not dynamic.  Additionally, this needs to be migrated to the 2024 robot once working.

**Comment by zaaj** [comment]
I used these two lines in:
FRC2022/Lamarr/src/main/java/frc/robot/Robot.java

    SmartDashboard.putString("BuildHost-BranchName", Robot.class.getPackage().getImplementationTitle());
    SmartDashboard.putString("GitCommitID-BuildTimestamp", Robot.class.getPackage().getImplementationVersion());

**Comment by zaaj** [comment]
Ok, in '22, we weren't using simulation yet. There's no Manifest when running in simulation, since the compiled Java files are not packaged into a JAR file. This means the two lines need to be wrapped in a string length check, since Smartdashboard.putstring() will error if given a null or empty string. I've committed a code stanza that does this, and doesn't crash in simulation, but haven't tested in a rio yet.
